import pygame

SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 720
BOARD_WIDTH, BOARD_HEIGHT = 821, 492
ROW_AMOUNT, COL_AMOUNT = 5, 9
FPS = 60

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
GREY = (128, 128, 128)
GREY_RED = (192, 64, 64)
WHITE_RED = (255, 128, 128)
BLACK_RED = (128, 0, 0)

PIECE_PADDING = 15
PIECE_OUTLINE = 2
DOT_SIZE = 10

SPACE_BETWEEN_PIECES = BOARD_WIDTH // (COL_AMOUNT + 1)
SPACE_LEFT_OF_PIECES = 314
SPACE_ABOVE_PIECES = 170

COL_RECT_SIZE = (BOARD_WIDTH // COL_AMOUNT, BOARD_HEIGHT)
ROW_RECT_SIZE = (BOARD_WIDTH, BOARD_HEIGHT // ROW_AMOUNT)
SPACE_EITHER_SIDE = (SCREEN_WIDTH - BOARD_WIDTH) // 2
SPACE_TOP_BOTTOM = (SCREEN_HEIGHT - BOARD_HEIGHT) // 2 - 24

# Rect((left, top), (width, height))
# cols
COL1_RECT = pygame.Rect((SPACE_EITHER_SIDE, SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL2_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0], SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL3_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0] * 2, SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL4_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0] * 3, SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL5_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0] * 4, SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL6_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0] * 5, SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL7_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0] * 6, SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL8_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0] * 7, SPACE_TOP_BOTTOM), COL_RECT_SIZE)
COL9_RECT = pygame.Rect((SPACE_EITHER_SIDE + COL_RECT_SIZE[0] * 8, SPACE_TOP_BOTTOM), COL_RECT_SIZE)

# rows
ROW1_RECT = pygame.Rect((SPACE_EITHER_SIDE, SPACE_TOP_BOTTOM), ROW_RECT_SIZE)
ROW2_RECT = pygame.Rect((SPACE_EITHER_SIDE, SPACE_TOP_BOTTOM + ROW_RECT_SIZE[1]), ROW_RECT_SIZE)
ROW3_RECT = pygame.Rect((SPACE_EITHER_SIDE, SPACE_TOP_BOTTOM + ROW_RECT_SIZE[1] * 2), ROW_RECT_SIZE)
ROW4_RECT = pygame.Rect((SPACE_EITHER_SIDE, SPACE_TOP_BOTTOM + ROW_RECT_SIZE[1] * 3), ROW_RECT_SIZE)
ROW5_RECT = pygame.Rect((SPACE_EITHER_SIDE, SPACE_TOP_BOTTOM + ROW_RECT_SIZE[1] * 4), ROW_RECT_SIZE)

ROW_RECTS = [ROW1_RECT, ROW2_RECT, ROW3_RECT, ROW4_RECT, ROW5_RECT]
COL_RECTS = [COL1_RECT, COL2_RECT, COL3_RECT, COL4_RECT, COL5_RECT, COL6_RECT, COL7_RECT, COL8_RECT, COL9_RECT]